### ISSUE TITLE
Message Caching and Smarter Logging

### ISSUE THREAD

**Issue by LogGits** [dniym/IllegalStack#206]
**Is your feature request related to a problem? Please describe.**
The current logging system generates individual messages for each violation, even when multiple similar violations occur in quick succession. This creates spam and makes it difficult to identify patterns of abuse.

**Describe the solution you'd like**
Implement a message caching system with these features:

Configuration options:
```yaml
smart_logging:
  enabled: true
  cache_duration: 30 # seconds
  minimum_stack: 3 # violations before stacking
  broadcast_interval: 60 # seconds
  exclusive_logs: # only log these types
    - bed_explosions
    - illegal_blocks
  # OR
  ignored_logs: # don't log these types
    - player_velocity
    - minor_violations
```    
Example output:
"[IllegalStack] Prevented 8 bed explosions in the last 30s at world(x: 100-150, y: 60-65, z: 200-220)"

**Additional context**
This system would make it easier to identify patterns of abuse while reducing log spam. The stacked messages would provide better context about the scale and location of violations.
